{% set version = "0.21.2" %}

package:
  name: spack
  version: {{ version }}
source:
  git_url: git@github.com:spack/spack.git
  git_rev: v{{ version }}
build:
  include_recipe: false
  missing_dso_whitelist:
    - "*/libc.so.6"
  noarch: python
  number: 0
  script: . share/spack/setup-env.sh && spack clone spack && rsync -av spack/ $PREFIX/
requirements:
  build:
    - python
    - rsync
about:
  license: APACHE
