{% set version = "0.21.2" %}

package:
  name: spack
  version: {{ version }}
source:
  url: https://github.com/spack/spack/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b1860537ba00c55fa0b2517ce9dbfe0e415600892c48e3dc4e15ee8da0f50dd3
build:
  include_recipe: false
  missing_dso_whitelist:
    - "*/libc.so.6"
  noarch: generic
  number: 0
requirements:
  build:
    - rsync
about:
  license: APACHE
