name: ci
env:
  ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
  GH_TOKEN: ${{ github.token }}
on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - '**'
jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check tag
        run:  .github/scripts/tag-check
      - name: Install conda
        run:  .github/scripts/install-conda
      - name: Build conda package
        run:  .github/scripts/conda-package-build
      - name: Publish conda package
        run: .github/scripts/conda-package-release
      - name: Tag
        run: .github/scripts/tag-create
